services:
  reverse-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PATH=/.well-known
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
 
 
  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: 'Lets-Encrypt'
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=Reverse-Proxy
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
 
  traveltrail-api:
      image: emiperezdev/traveltrail-api:latest
      container_name: traveltrail-api
      expose:
        - "3000"
      depends_on:
        - mongo
      environment:
        MONGO_URL: ${MONGO_URL}
        PORT: ${PORT}
        MONGO_DB: ${MONGO_DB}
        MAILER_ACCESS_TOKEN: ${MAILER_ACCESS_TOKEN}
        MAILER_SERVICE: ${MAILER_SERVICE}
        MAILER_EMAIL: ${MAILER_EMAIL}
        MAILER_EMAIL_DESTINATION: ${MAILER_EMAIL_DESTINATION}
        MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
        LETSENCRYPT_HOST: ${DOMAIN}
        LETSENCRYPT_EMAIL: ${MAILER_EMAIL}
        LETSENCRYPT_EMAIL_DESTINATION: ${MAILER_EMAIL_DESTINATION}
        VIRTUAL_HOST: ${DOMAIN}
        VIRTUAL_PATH: /
  
  mongo:
    image: mongo
    container_name: mongo-traveltrail
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
    - "27018:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: